version: 0.0.1.{build}

shallow_clone: true

environment:
  GHC_REV: bee827178f3825356e958adcc9ffbaf5896ef1bd

build_script:
  - cmd: |
      choco install haskell-stack
      git clone git://git.haskell.org/ghc.git
      cd ghc
      git checkout %GHC_REV%
      git submodule update --init --recursive
      C:\msys64\msys2_shell.cmd -mingw64 -defterm -no-start -e /C/projects/asterius/.appveyor/build.sh

artifacts:
  - path: 'ghc\*.tar.xz'
    name: ghc
