resolver: ghc-8.7
allow-newer: true
flags:
  hashable:
    integer-gmp: false
  integer-logarithms:
    integer-gmp: false
  scientific:
    integer-simple: true
extra-deps:
  - ansi-terminal-0.8.0.4
  - ansi-wl-pprint-0.6.8.2
  - attoparsec-0.13.2.2
  - base-compat-0.10.4
  - https://github.com/TerrorJack/cereal/archive/Serialize-instance-ShortByteString.zip
  - colour-2.3.4
  - dlist-0.8.0.4
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - integer-logarithms-1.0.2.1
  - mintty-0.1.2
  - optparse-applicative-0.14.2.0
  - pretty-show-1.8.1
  - https://github.com/haskell/primitive/archive/ff65e8e3a415eba7ba9b20ea83cd08cb3d601b26.zip
  - scientific-0.3.6.2
  - transformers-compat-0.6.2
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
packages:
  - asterius
  - binaryen
  - genapply
  - ghc-toolkit
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.7.20180821:
        url: https://ci.appveyor.com/api/buildjobs/mlrtwky0nd41m3y7/artifacts/ghc/ghc-8.7.20180821-x86_64-unknown-mingw32.tar.xz
    linux64:
      8.7.20180821:
        url: https://1554-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.7.20180821-x86_64-unknown-linux.tar.xz
