version: 2

jobs:
  vanilla:
    resource_class: xlarge
    docker:
      - image: ubuntu:bionic
    environment:
      DEBIAN_FRONTEND: noninteractive
      GHC_REV: bee827178f3825356e958adcc9ffbaf5896ef1bd
      JOBS: 9
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y software-properties-common
            add-apt-repository -y ppa:hvr/ghc
            apt update
            apt dist-upgrade -y
            apt install -y \
              alex-3.1.7 \
              autoconf \
              automake \
              cabal-install-2.2 \
              clang-5.0 \
              g++ \
              ghc-8.4.3 \
              git \
              happy-1.19.5 \
              libffi-dev \
              libgmp-dev \
              libncurses5-dev \
              libnuma-dev \
              libtool-bin \
              make \
              pkg-config \
              python3-sphinx \
              xz-utils \
              zlib1g-dev
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone git://git.haskell.org/ghc.git
            cd ghc
            git checkout $GHC_REV
            git submodule update --init --recursive
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=$PATH:~/.cabal/bin:/opt/ghc/8.4.3/bin:/opt/cabal/2.2/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:/usr/share/sphinx/scripts/python3
            cabal update
            cabal install hscolour
            mv .circleci/build.mk /tmp/ghc/mk/
            cd /tmp/ghc
            ./boot
            ./configure
            make -j$JOBS
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
      - store_artifacts:
          path: /tmp/ghc-bindist

  lambda:
    resource_class: xlarge
    docker:
      - image: lambci/lambda:build-nodejs8.10
    environment:
      GHC_REV: bee827178f3825356e958adcc9ffbaf5896ef1bd
      JOBS: 9
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            yum -y install ncurses-devel
            mkdir -p ~/.local/bin
            export PATH=~/.local/bin:$PATH
            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            stack --no-terminal --resolver nightly install \
              alex \
              happy
      - run:
          name: Initialize ghc repo
          command: |
            mkdir /tmp/ghc-git
            cd /tmp/ghc-git
            git clone git://git.haskell.org/ghc.git
            cd ghc
            git checkout $GHC_REV
            git submodule update --init --recursive
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$(~/.local/bin/stack path --compiler-bin):$PATH
            cp .circleci/build-lambda.mk /tmp/ghc-git/ghc/mk/build.mk
            cd /tmp/ghc-git/ghc
            ./boot
            ./configure --prefix=/tmp/ghc
            make -j$JOBS
            make install
            cd /tmp
            tar cfJ ghc.tar.xz ghc
      - store_artifacts:
          path: /tmp/ghc.tar.xz

workflows:
  version: 2
  build:
    jobs:
      - vanilla
      - lambda
